
Simulink.Bus.cellToObject(...
    {{ ...
    'CORE', ...
    '', ...
    '', ...
    [ ...
    {{'time', 1, 'double', -1 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'CAM', ...
    '', ...
    '', ...
    [ ...
    {{'line_angle', 1, 'double', -1 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'object_id', 10, 'double', -1 'real', 'Sample', 'Fixed'}} ...
    {{'object_angle', 10, 'double', -1 'real', 'Sample', 'Fixed'}} ...
    {{'car_check_flag', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'accident_flag', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ... 
    {{'bad_lane_flag', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'LIDAR', ...
    '', ...
    '', ...
    [ ...
    {{'detected_number', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'angle', 10, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'dist', 10, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'OUTPUT', ...
    '', ...
    '', ...
    [ ...
    {{'front_car_speed', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'overfast_flag', 1, 'uint8', -1, 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'lane_change_flag', 1, 'uint8', -1, 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'bad_lane_flag', 1, 'uint8', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'accident_flag', 1, 'uint8', -1, 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'MCU_CONTROL', ...
    '', ...
    '', ...
    [ ...
    {{'steering_angle', 1, 'uint16', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'speed', 1, ' uint16', -1, 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'blinker_onoff', 1, 'uint8', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'blinker_dir', 1, 'uint8', -1, 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'break_light_onoff', 1, 'uint8', -1, 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'CHECK', ...
    '', ...
    '', ...
    [ ...
    {{'car_check_flag', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ...
    {{'object_angle', 1, 'double', -1 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'lidar_bus', 1, 'Bus: LIDAR', -1, 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'CHECK', ...
    '', ...
    '', ...
    [ ...
    {{'object_id', 10, 'double', -1 'real', 'Sample', 'Fixed'}} ...
    {{'object_angle', 10, 'double', -1 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'car_check_flag', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'detected_number', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'angle', 10, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'dist', 10, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

