
Simulink.Bus.cellToObject(...
    {{ ...
    'CORE', ...
    '', ...
    '', ...
    [ ...
    {{'time', 1, 'double', -1 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'CAM', ...
    '', ...
    '', ...
    [ ...
    {{'line_angle', 1, 'double', -1 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'car_check_flag', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ...
    {{'object_angle', 1, 'double', -1 'real', 'Sample', 'Fixed'}} ...
    {{'accident_flag', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ... 
    {{'accident_angle', 1, 'uint16', -1 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'bad_lane_flag', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'LIDAR', ...
    '', ...
    '', ...
    [ ...
    {{'angle_fov', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'dist_fov', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'angle_nfov', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'dist_nfov', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'OUTPUT', ...
    '', ...
    '', ...
    [ ...
    {{'steering_angle', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'next_vel', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'front_car_vel', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'lane_change_flag', 1, 'uint8', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'overfast_flag', 1, 'uint8', -1, 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'bad_lane_flag', 1, 'uint8', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'accident_flag', 1, 'uint8', -1, 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'CHECK', ...
    '', ...
    '', ...
    [ ...
    {{'car_check_flag', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ...
    {{'object_angle', 1, 'double', -1 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'angle_fov', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'dist_fov', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'angle_nfov', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'dist_nfov', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'ACCIDENT', ...
    '', ...
    '', ...
    [ ...
    {{'accident_flag', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ... 
    {{'accident_angle', 1, 'uint16', -1 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'angle_fov', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'dist_fov', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'angle_nfov', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'dist_nfov', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})
