
Simulink.Bus.cellToObject(...
    {{ ...
    'CORE', ...
    '', ...
    '', ...
    [ ...
    {{'time', 1, 'int32', -1 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'CAM', ...
    '', ...
    '', ...
    [ ...
    {{'line_angle', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'object_id', 10, 'uint8', -1 'real', 'Sample', 'Fixed'}} ...
    {{'object_angle', 10, 'uint16', -1 'real', 'Sample', 'Fixed'}} ...
    {{'car_check_flag', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'crack_flag', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ... 
    ...
    {{'sig_flag', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ...
    {{'stop_line_dist', 1, 'double', -1 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'change_lane_dir', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'SIGNAL', ...
    '', ...
    '', ...
    [ ...
    {{'sig_flag', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ...
    {{'stop_line_dist', 1, 'double', -1 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'LIDAR', ...
    '', ...
    '', ...
    [ ...
    {{'detected_number', 1, 'uint8', -1, 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'angle', 10, 'uint16', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'dist', 10, 'uint16', -1, 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'OBJECT', ...
    '', ...
    '', ...
    [ ...
    {{'who', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ...
    {{'id', 1, 'uint32', -1 'real', 'Sample', 'Fixed'}} ...
    {{'dist', 1, 'uint32', -1 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'CRUISER', ...
    '', ...
    '', ...
    [ ...
    {{'line_angle', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ...
    {{'car_check_flag', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'change_lane_dir', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'C_BUS', ...
    '', ...
    '', ...
    [ ...
    {{'object_id', 10, 'uint8', -1 'real', 'Sample', 'Fixed'}} ...
    {{'object_angle', 10, 'uint16', -1 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'change_lane_dir', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'OUTPUT', ...
    '', ...
    '', ...
    [ ...
    {{'front_car_speed', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'overfast_flag', 1, 'uint8', -1, 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'signal_violation_flag', 1, 'uint8', -1, 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'crack_flag', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'MCU_CONTROL', ...
    '', ...
    '', ...
    [ ...
    {{'steering_angle', 1, 'uint8', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'speed', 1, ' uint8', -1, 'real', 'Sample', 'Fixed'}} ...
    ...
    {{'blinker_onoff', 1, 'uint8', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'blinker_dir', 1, 'uint8', -1, 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})
