Simulink.Bus.cellToObject(...
    {{ ...
    'CAM', ...
    '', ...
    '', ...
    [ ...
    {{'input_CAM_line_angle', 1, 'double', -1 'real', 'Sample', 'Fixed'}} ...
    {{'input_CAM_object_angle', 1, 'uint16', -1 'real', 'Sample', 'Fixed'}} ...
    {{'input_CAM_accident_location', 1, 'uint16', -1 'real', 'Sample', 'Fixed'}} ...
    {{'input_CAM_bad_lane_flag', 1, 'uint16', -1 'real', 'Sample', 'Fixed'}} ...
    {{'input_CAM_accident_flag', 1, 'uint16', -1 'real', 'Sample', 'Fixed'}} ...  
    {{'input_CAM_car_check_flag', 1, 'uint16', -1 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'LIDAR', ...
    '', ...
    '', ...
    [ ...
    {{'input_LIDAR_angle_fov', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'input_LIDAR_dist_fov', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'input_LIDAR_angle_nfov', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'input_LIDAR_dist_nfov', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'CONTROL', ...
    '', ...
    '', ...
    [ ...
    {{'input_CTR_prev_speed', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'input_CTR_next_speed', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'OUTPUT', ...
    '', ...
    '', ...
    [ ...
    {{'output_sterring_angle', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'output_front_car_vel', 1, 'double', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'output_user_vel', 1, 'uint16', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'output_overfast_flag', 1, 'uint16', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'output_bad_lane_flag', 1, 'uint16', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'output_lane_change_flag', 1, 'uint16', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'output_accident_flag', 1, 'uint16', -1, 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})
